device_type: PLACEHOLDER_DEVICE_TYPE
job_name: PLACEHOLDER_JOB_NAME
priority: medium
visibility: public

timeouts:
  job:
    minutes: 20
  action:
    minutes: 10
  connection:
    minutes: 2

actions:
