include:
  - /ci/whinlatter.yml
  - /ci/scarthgap.yml
  - /ci/kirkstone.yml

stages:
  - pre-flight-checks
  - build:whinlatter
  - build:scarthgap
  - build:kirkstone
  - test:whinlatter
  - test:scarthgap
  - test:kirkstone
  - yocto-check-layer
  - deploy
  - release

variables:
  BUILD_OUTPUT_DIR_TOP: build_output
  CI_MINIO_ALIAS: "spl2-build-artifacts-be"
  CI_MINIO_BROWSER: "http://10.226.35.98:9001/browser"
  CI_MINIO_BUCKET: "rz-community-bsp"
  CI_MINIO_SERVER: "http://10.226.35.98:9000"
  # CI_MINIO_USER and CI_MINIO_PASS need to be defined in GitLab CI

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_TAG

.yocto-check-layer-base:
  stage: yocto-check-layer
  image: ghcr.io/siemens/kas/kas:4.8.2
  tags:
    - ree-du1sdd1
    - spl2
    - yocto
  needs: []
  script:
    - kas shell --update --force-checkout ${CI_KAS_CONFIG} -c \
      "yocto-check-layer-wrapper ${CI_PROJECT_DIR}/meta-rz-bsp --dependency ${CI_PROJECT_DIR}/meta-arm/meta-arm ${CI_PROJECT_DIR}/meta-arm/meta-arm-toolchain ${CI_PROJECT_DIR}/meta-openembedded/meta-oe ${CI_PROJECT_DIR}/poky/meta ${CI_PROJECT_DIR}/poky/meta-poky --no-auto-dependency --machines hihope-rzg2h hihope-rzg2m hihope-rzg2n ek874 smarc-rzg2l smarc-rzg2lc smarc-rzg2ul smarc-rzv2l"

pre-commit:
  stage: pre-flight-checks
  image: ubuntu:24.04
  before_script:
    - apt update && apt install -y git pipx
    - pipx install pre-commit
    - export PATH=~/.local/bin:$PATH
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
  script:
    - pre-commit run -a

deploy-binaries:
  stage: deploy
  image: gitlab.global.renesas.com:5005/spl2/continuous-integration/dockerfiles:ubuntu-24.04-latest
  tags:
    - small
    - spl2
  dependencies: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - mc alias set ${CI_MINIO_ALIAS} ${CI_MINIO_SERVER} ${CI_MINIO_USER} ${CI_MINIO_PASS}
    - echo "Copying test binaries to production directory on spl2-build-artifacts-be..."
    - mc mirror --retry --overwrite --remove ${CI_MINIO_ALIAS}/${CI_MINIO_BUCKET}/ci/${CI_PIPELINE_ID}/ ${CI_MINIO_ALIAS}/${CI_MINIO_BUCKET}/latest/
    - 'echo "Download URL: ${CI_MINIO_BROWSER}/${CI_MINIO_BUCKET}/latest/"'

push-to-github:
  stage: release
  image: ubuntu:24.04
  dependencies: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - apt update && apt install -y git
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
  script:
    - git remote remove github || true
    - git remote add github "https://GITHUB_DEPLOY_TOKEN:$GITHUB_DEPLOY_TOKEN@github.com/renesas-rz/rz-community-bsp.git"
    - git push -f github HEAD:whinlatter
    - git push -f github HEAD:scarthgap
    - git push -f github HEAD:kirkstone

### BUILDING ###
.build-base:
  image: ghcr.io/siemens/kas/kas:4.8.2
  tags:
    - spl2
    - yocto
  needs: []
  before_script:
    - find dependencies -name "*tar.gz" -exec tar xf '{}' \; || true
  after_script:
    - mkdir -p dependencies
    - |
      for repo in meta-arm meta-linux-mainline meta-openembedded meta-rz-panfrost poky; do
        if [ -d "${repo}" ]; then
          tar czf dependencies/"${repo}".tar.gz "${repo}"
        fi
      done
  cache:
    - key: "dependencies"
      paths:
        - dependencies

.copy-output: &copy-output
    - export BUILD_OUTPUT_DIR=${BUILD_OUTPUT_DIR_TOP}/${CI_BITBAKE_MACHINE}/${CI_BITBAKE_IMAGE}/${BUILD_NAME}
    - mkdir -p ${BUILD_OUTPUT_DIR}
    - cp -L scripts/lava-env/${CI_BITBAKE_MACHINE}.env ${BUILD_OUTPUT_DIR}
    - echo "ROOTFS=${CI_BITBAKE_IMAGE}-${CI_BITBAKE_MACHINE}.tar.gz" >> ${BUILD_OUTPUT_DIR}/${CI_BITBAKE_MACHINE}.env
    - source ${BUILD_OUTPUT_DIR}/${CI_BITBAKE_MACHINE}.env
    - cp -r build/conf ${BUILD_OUTPUT_DIR}
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${BUILD_OUTPUT_DIR}
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${BUILD_OUTPUT_DIR}
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${BUILD_OUTPUT_DIR}
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${FW} ${BUILD_OUTPUT_DIR} || true
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${BL2} ${BUILD_OUTPUT_DIR} || true
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${FIP} ${BUILD_OUTPUT_DIR} || true
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${SA0} ${BUILD_OUTPUT_DIR} || true
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${SA6} ${BUILD_OUTPUT_DIR} || true
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${BL31} ${BUILD_OUTPUT_DIR} || true
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${UBOOT} ${BUILD_OUTPUT_DIR} || true
    - tar czf licenses.tar.gz build/tmp/deploy/licenses
    - cp licenses.tar.gz ${BUILD_OUTPUT_DIR}

.upload-artifacts: &upload-artifacts
    # Install Minio client
    - curl -Lso mc https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc alias set ${CI_MINIO_ALIAS} ${CI_MINIO_SERVER} ${CI_MINIO_USER} ${CI_MINIO_PASS}
    # Upload test artifacts to fileserver
    - UPLOAD_PATH="ci/${CI_PIPELINE_ID}/${CI_YOCTO_VER}"
    - echo "Uploading test binaries to spl2-build-artifacts-be..."
    - ./mc cp -r --quiet ${BUILD_OUTPUT_DIR_TOP}/${CI_BITBAKE_MACHINE} ${CI_MINIO_ALIAS}/${CI_MINIO_BUCKET}/${UPLOAD_PATH}/
    - 'echo "Download URL: ${CI_MINIO_BROWSER}/${CI_MINIO_BUCKET}/${UPLOAD_PATH}/${CI_BITBAKE_MACHINE}/"'

.build-g2h-family-mainline: &build-g2h-family-mainline
    # kernel: mainline
    # u-boot: mainline-2024.10
    # tf-a: mainline-2.10.8
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/mainline.yml:kas/u-boot/mainline-2024.10.yml:kas/trusted-firmware-a/mainline-2.10.8.yml
    - export BUILD_NAME="mainline"
    - *copy-output

.build-g2h-family-lts-66: &build-g2h-family-lts-66
    # kernel: lts-6.6
    # u-boot: mainline-2024.10
    # tf-a: mainline-2.10.8
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/lts-6.6.yml:kas/u-boot/mainline-2024.10.yml:kas/trusted-firmware-a/mainline-2.10.8.yml
    - export BUILD_NAME="lts-6.6"
    - *copy-output

.build-g2h-family-lts-612: &build-g2h-family-lts-612
    # kernel: lts-6.12
    # u-boot: mainline-2024.10
    # tf-a: mainline-2.10.8
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/lts-6.12.yml:kas/u-boot/mainline-2024.10.yml:kas/trusted-firmware-a/mainline-2.10.8.yml
    - export BUILD_NAME="lts-6.12"
    - *copy-output

.build-g2h-family-cip-510: &build-g2h-family-cip-510
    # kernel: cip-5.10
    # u-boot: mainline-2024.10
    # tf-a: mainline-2.10.8
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-5.10.yml:kas/u-boot/mainline-2024.10.yml:kas/trusted-firmware-a/mainline-2.10.8.yml
    - export BUILD_NAME="cip-5.10"
    - *copy-output

.build-g2h-family-cip-61: &build-g2h-family-cip-61
    # kernel: cip-6.1
    # u-boot: mainline-2024.10
    # tf-a: mainline-2.10.8
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-6.1.yml:kas/u-boot/mainline-2024.10.yml:kas/trusted-firmware-a/mainline-2.10.8.yml
    - export BUILD_NAME="cip-6.1"
    - *copy-output

.build-g2h-family-cip-612: &build-g2h-family-cip-612
    # kernel: cip-6.12
    # u-boot: mainline-2024.10
    # tf-a: mainline-2.10.8
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-6.12.yml:kas/u-boot/mainline-2024.10.yml:kas/trusted-firmware-a/mainline-2.10.8.yml
    - export BUILD_NAME="cip-6.12"
    - *copy-output

.build-g2h-family-bsp: &build-g2h-family-bsp
    # kernel: renesas-5.10
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/renesas-5.10.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="renesas-5.10"
    - *copy-output

.build-g2l-family-mainline: &build-g2l-family-mainline
    # Mainline bootloaders do not support this family yet
    # kernel: mainline
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/mainline.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="mainline"
    - *copy-output

.build-g2l-family-lts-66: &build-g2l-family-lts-66
    # Mainline bootloaders do not support this family yet
    # kernel: lts-6.6
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/lts-6.6.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="lts-6.6"
    - *copy-output

.build-g2l-family-lts-612: &build-g2l-family-lts-612
    # Mainline bootloaders do not support this family yet
    # kernel: lts-6.12
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/lts-6.12.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="lts-6.12"
    - *copy-output

.build-g2l-family-cip-510: &build-g2l-family-cip-510
    # kernel: cip-5.10
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-5.10.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="cip-5.10"
    - *copy-output

.build-g2l-family-cip-61: &build-g2l-family-cip-61
    # kernel: cip-6.1
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-6.1.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="cip-6.1"
    - *copy-output

.build-g2l-family-cip-612: &build-g2l-family-cip-612
    # kernel: cip-6.12
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-6.12.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="cip-6.12"
    - *copy-output

.build-g2l-family-bsp: &build-g2l-family-bsp
    # kernel: renesas-5.10
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/renesas-5.10.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - export BUILD_NAME="renesas-5.10"
    - *copy-output

.kirkstone:
  variables:
    CI_YOCTO_VER: kirkstone

.build-kirkstone:
  stage: build:kirkstone
  extends: .kirkstone
  variables:
    CI_KAS_YOCTO: kas/yocto/kirkstone.yml

.kirkstone-g2h-family:
  extends: .build-kirkstone
  script:
    - *build-g2h-family-cip-510
    - *build-g2h-family-cip-61
    - *build-g2h-family-cip-612
    - *build-g2h-family-bsp
    - *upload-artifacts

.kirkstone-g2l-family:
  extends: .build-kirkstone
  script:
    - *build-g2l-family-cip-510
    - *build-g2l-family-cip-61
    - *build-g2l-family-cip-612
    - *build-g2l-family-bsp
    - *upload-artifacts

.scarthgap:
  variables:
    CI_YOCTO_VER: scarthgap

.build-scarthgap:
  stage: build:scarthgap
  extends: .scarthgap
  variables:
    CI_KAS_YOCTO: kas/yocto/scarthgap.yml

.scarthgap-g2h-family:
  extends: .build-scarthgap
  script:
    - *build-g2h-family-mainline
    - *build-g2h-family-lts-66
    - *build-g2h-family-lts-612
    - *build-g2h-family-cip-510
    - *build-g2h-family-cip-61
    - *build-g2h-family-cip-612
    - *build-g2h-family-bsp
    - *upload-artifacts

.scarthgap-g2l-family:
  extends: .build-scarthgap
  script:
    - *build-g2l-family-mainline
    - *build-g2l-family-lts-66
    - *build-g2l-family-lts-612
    - *build-g2l-family-cip-510
    - *build-g2l-family-cip-61
    - *build-g2l-family-cip-612
    - *build-g2l-family-bsp
    - *upload-artifacts

.whinlatter:
  variables:
    CI_YOCTO_VER: whinlatter

.build-whinlatter:
  stage: build:whinlatter
  extends: .whinlatter
  variables:
    CI_KAS_YOCTO: kas/yocto/whinlatter.yml

.whinlatter-g2h-family:
  extends: .build-whinlatter
  script:
    - *build-g2h-family-mainline
    - *build-g2h-family-lts-66
    - *build-g2h-family-lts-612
    - *build-g2h-family-cip-510
    - *build-g2h-family-cip-61
    - *build-g2h-family-cip-612
    - *build-g2h-family-bsp
    - *upload-artifacts

.whinlatter-g2l-family:
  extends: .build-whinlatter
  script:
    - *build-g2l-family-mainline
    - *build-g2l-family-lts-66
    - *build-g2l-family-lts-612
    - *build-g2l-family-cip-510
    - *build-g2l-family-cip-61
    - *build-g2l-family-cip-612
    - *build-g2l-family-bsp
    - *upload-artifacts

.build-sdk:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
  variables:
    BUILD_NAME: sdk
    SDK_TMP: sdk-tmp
  script:
    # Create SDK
    # kernel: default
    # u-boot: default
    # tf-a: default
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE} --cmd populate_sdk
    - export BUILD_OUTPUT_DIR=${BUILD_OUTPUT_DIR_TOP}/${CI_BITBAKE_MACHINE}/${CI_BITBAKE_IMAGE}/${BUILD_NAME}
    - mkdir -p ${BUILD_OUTPUT_DIR}
    - cp -r build/conf ${BUILD_OUTPUT_DIR}
    - cp -r build/tmp/deploy/sdk ${BUILD_OUTPUT_DIR}
    # Create rootfs for testing
    # kernel: default
    # u-boot: default
    # tf-a: default
    - kas build --update --force-checkout kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}
    - *copy-output
    # Install SDK
    - rm -rf ${SDK_TMP}
    - mkdir -p ${SDK_TMP}
    - sudo chmod +x ${BUILD_OUTPUT_DIR}/sdk/poky-*.sh
    - ${BUILD_OUTPUT_DIR}/sdk/poky-*.sh -d ${SDK_TMP}/ -y
    # Compile test application
    - source ${SDK_TMP}/environment-setup-*
    - ${CC} -o ${SDK_TMP}/hello-test scripts/hello.c
    - file ${SDK_TMP}/hello-test
    - cp ${SDK_TMP}/hello-test ${BUILD_OUTPUT_DIR}/
    # Add test application to rootfs for on target testing
    - mkdir -p ${SDK_TMP}/rootfs
    - tar xf ${BUILD_OUTPUT_DIR}/${ROOTFS} -C ${SDK_TMP}/rootfs
    - cp ${SDK_TMP}/hello-test ${SDK_TMP}/rootfs/usr/bin
    - pushd ${SDK_TMP}/rootfs/
    - tar czf ../${ROOTFS} *
    - popd
    - cp ${SDK_TMP}/${ROOTFS} ${BUILD_OUTPUT_DIR}
    - *upload-artifacts

.renesas-image-minimal:
  variables:
    CI_BITBAKE_IMAGE: renesas-image-minimal
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml

.renesas-image-demo:
  variables:
    CI_BITBAKE_IMAGE: renesas-image-demo
    CI_KAS_IMAGE: kas/image/renesas-image-demo.yml

.hihope-rzg2h:
  variables:
    CI_BITBAKE_MACHINE: hihope-rzg2h
    CI_KAS_MACHINE: kas/machine/hihope-rzg2h.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-uboot.yaml

.hihope-rzg2m:
  variables:
    CI_BITBAKE_MACHINE: hihope-rzg2m
    CI_KAS_MACHINE: kas/machine/hihope-rzg2m.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-uboot.yaml

.hihope-rzg2n:
  variables:
    CI_BITBAKE_MACHINE: hihope-rzg2n
    CI_KAS_MACHINE: kas/machine/hihope-rzg2n.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-uboot.yaml

.ek874:
  variables:
    CI_BITBAKE_MACHINE: ek874
    CI_KAS_MACHINE: kas/machine/ek874.yml
    LAVACLI_IDENTITY: magma

.smarc-rzg2l:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2l
    CI_KAS_MACHINE: kas/machine/smarc-rzg2l.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-fip.yaml

.smarc-rzg2lc:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2lc
    CI_KAS_MACHINE: kas/machine/smarc-rzg2lc.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-fip.yaml

.smarc-rzg2ul:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2ul
    CI_KAS_MACHINE: kas/machine/smarc-rzg2ul.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-fip.yaml

.smarc-rzv2l:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzv2l
    CI_KAS_MACHINE: kas/machine/smarc-rzv2l.yml
    LAVACLI_IDENTITY: magma
    FLASH_TEMPLATE: flash-fip.yaml


### TESTING ###
.test-base:
  image: gitlab.global.renesas.com:5005/spl2/continuous-integration/dockerfiles:ubuntu-24.04-latest
  tags:
    - spl2
    - lava-job
  variables:
    MINIO_DL_URL: "${CI_MINIO_SERVER}/${CI_MINIO_BUCKET}/ci/${CI_PIPELINE_ID}/${CI_YOCTO_VER}/${CI_BITBAKE_MACHINE}/${CI_BITBAKE_IMAGE}/${BUILD_NAME}/"
  script:
    - mkdir -p results
    - echo "ROOTFS=${CI_BITBAKE_IMAGE}-${CI_BITBAKE_MACHINE}.tar.gz" >> scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - scripts/submit-lava-job.sh -i ${LAVACLI_IDENTITY} -d -u spl2-bot -e scripts/lava-env/${CI_BITBAKE_MACHINE}.env -j results -B ${MINIO_DL_URL} ${TEMPLATES} ${TESTS}
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 1 year
    reports:
      junit: results/results*.xml
    paths:
      - results

.test-base-sdk:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
      allow_failure: true
  extends: [.test-base]

.lava-templates-standard:
  variables:
    TEMPLATES: "-l scripts/lava-templates/base.yaml -l scripts/lava-templates/deploy.yaml -l scripts/lava-templates/boot.yaml"

.lava-templates-bootloader:
  variables:
    TEMPLATES: "-l scripts/lava-templates/base.yaml -l scripts/lava-templates/${FLASH_TEMPLATE} -l scripts/lava-templates/deploy.yaml -l scripts/lava-templates/boot.yaml"

.standard-test-cases:
  variables:
    TESTS: "-t scripts/lava-templates/test-uname.yaml"

.sdk-test-cases:
  variables:
    TESTS: "-t scripts/lava-templates/test-sdk-hello.yaml"
